name: project2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  animations: ^2.0.7
  convex_bottom_bar: ^3.2.0
  country_picker: ^2.0.20
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.0.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  shimmer: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  http: 0.13.5
  lottie: 2.6.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/background/
    - assets/images/books/
    - assets/images/lottie/
    - assets/empty/
    - assets/bank/
  uses-material-design: true

